Repository Renondedju/Ruken, pull requests merged in 2020-03, with the labels that each got.

#4 Fixed getting debug informations in release mode
  DaemonRenderer.sln
Labels: Bug

#5 Containers simplification
  DaemonRenderer/DaemonRenderer.vcxproj
  DaemonRenderer/Source/Include/Config.hpp
  DaemonRenderer/Source/Include/Containers/Array.hpp
  DaemonRenderer/Source/Include/Containers/Bitset.hpp
  DaemonRenderer/Source/Include/Containers/Deque.hpp
  DaemonRenderer/Source/Include/Containers/ForwardList.hpp
  DaemonRenderer/Source/Include/Containers/List.hpp
  DaemonRenderer/Source/Include/Containers/Map.hpp
  DaemonRenderer/Source/Include/Containers/Pair.hpp
  DaemonRenderer/Source/Include/Containers/Queue.hpp
  DaemonRenderer/Source/Include/Containers/Set.hpp
  DaemonRenderer/Source/Include/Containers/SmartPtr.hpp
  DaemonRenderer/Source/Include/Containers/Stack.hpp
  DaemonRenderer/Source/Include/Containers/String.hpp
  DaemonRenderer/Source/Include/Containers/Tuple.hpp
  DaemonRenderer/Source/Include/Containers/UnorderedMap.hpp
  DaemonRenderer/Source/Include/Containers/UnorderedSet.hpp
  DaemonRenderer/Source/Include/Containers/Vector.hpp
  DaemonRenderer/Source/Include/Debug/Logging/Formatters/ConsoleFormatter.hpp
  DaemonRenderer/Source/Include/Debug/Logging/Formatters/LogFormatter.hpp
  DaemonRenderer/Source/Include/Debug/Logging/Handlers/FileHandler.hpp
  DaemonRenderer/Source/Include/Debug/Logging/Handlers/LogHandler.hpp
  DaemonRenderer/Source/Include/Debug/Logging/LogRecord.hpp
  DaemonRenderer/Source/Include/Debug/Logging/Logger.hpp
  DaemonRenderer/Source/Include/ECS/ComponentItem.hpp
  DaemonRenderer/Source/Include/ECS/EntityAdmin.hpp
  DaemonRenderer/Source/Include/Functional/Event.hpp
  DaemonRenderer/Source/Include/Resource/Enums/EResourceLoadingFailureCode.hpp
  DaemonRenderer/Source/Include/Resource/ResourceIdentifier.hpp
  DaemonRenderer/Source/Include/Resource/ResourceManager.hpp
  DaemonRenderer/Source/Include/Resource/ResourceProcessingFailure.hpp
  DaemonRenderer/Source/Include/Threading/Scheduler.hpp
  DaemonRenderer/Source/Include/Threading/ThreadSafeLockQueue.hpp
  DaemonRenderer/Source/Include/Threading/Worker.hpp
  DaemonRenderer/Source/Include/Windowing/Screen.hpp
  DaemonRenderer/Source/Include/Windowing/Utility.hpp
  DaemonRenderer/Source/Include/Windowing/Window.hpp
  DaemonRenderer/Source/Include/Windowing/WindowManager.hpp
  DaemonRenderer/Source/Src/Debug/Logging/Formatters/ConsoleFormatter.cpp
  DaemonRenderer/Source/Src/Debug/Logging/Formatters/LogFormatter.cpp
  DaemonRenderer/Source/Src/Debug/Logging/Handlers/FileHandler.cpp
  DaemonRenderer/Source/Src/Debug/Logging/Handlers/LogHandler.cpp
  DaemonRenderer/Source/Src/Debug/Logging/LogRecord.cpp
  DaemonRenderer/Source/Src/Debug/Logging/Logger.cpp
  DaemonRenderer/Source/Src/Resource/Exceptions/ResourceProcessingFailure.cpp
  DaemonRenderer/Source/Src/Resource/ResourceIdentifier.cpp
  DaemonRenderer/Source/Src/Resource/ResourceManager.cpp
  DaemonRenderer/Source/Src/Threading/Worker.cpp
  DaemonRenderer/Source/Src/Windowing/Screen.cpp
  DaemonRenderer/Source/Src/Windowing/Window.cpp
  DaemonRenderer/Source/Src/Windowing/WindowManager.cpp
  DaemonRenderer/Source/ThirdParty/GLFW/glfw3.h
  DaemonRenderer/Source/ThirdParty/Vulkan/vulkan.hpp
Labels: Refactoring

#6 Major code cleanup
  DaemonRenderer/DaemonRenderer.vcxproj
  DaemonRenderer/Source/Include/Bitwise/Bitmask.hpp
  DaemonRenderer/Source/Include/Bitwise/Endian.hpp
  DaemonRenderer/Source/Include/Bitwise/SizedBitmask.hpp
  DaemonRenderer/Source/Include/Config.hpp
  DaemonRenderer/Source/Include/Debug/Logging/Filters/LogFilter.hpp
  DaemonRenderer/Source/Include/Debug/Logging/Formatters/ConsoleFormatter.hpp
  DaemonRenderer/Source/Include/Debug/Logging/Formatters/FileFormatter.hpp
  DaemonRenderer/Source/Include/Debug/Logging/Formatters/LogFormatter.hpp
  DaemonRenderer/Source/Include/Debug/Logging/Handlers/FileHandler.hpp
  DaemonRenderer/Source/Include/Debug/Logging/Handlers/LogHandler.hpp
  DaemonRenderer/Source/Include/Debug/Logging/Handlers/StreamHandler.hpp
  DaemonRenderer/Source/Include/Debug/Logging/LogLevel.hpp
  DaemonRenderer/Source/Include/Debug/Logging/LogRecord.hpp
  DaemonRenderer/Source/Include/Debug/Logging/Logger.hpp
  DaemonRenderer/Source/Include/Debug/RenderDoc/RenderDocHook.hpp
  DaemonRenderer/Source/Include/Functional/Event.hpp
  DaemonRenderer/Source/Include/Functional/ReservedEvent.hpp
  DaemonRenderer/Source/Include/Windowing/Screen.hpp
  DaemonRenderer/Source/Include/Windowing/Window.hpp
  DaemonRenderer/Source/Include/Windowing/WindowManager.hpp
  DaemonRenderer/Source/Src/Debug/Logging/Formatters/ConsoleFormatter.cpp
  DaemonRenderer/Source/Src/Debug/Logging/Formatters/FileFormatter.cpp
  DaemonRenderer/Source/Src/Debug/Logging/Formatters/LogFormatter.cpp
  DaemonRenderer/Source/Src/Debug/Logging/Handlers/FileHandler.cpp
  DaemonRenderer/Source/Src/Debug/Logging/Handlers/LogHandler.cpp
  DaemonRenderer/Source/Src/Debug/Logging/Handlers/StreamHandler.cpp
  DaemonRenderer/Source/Src/Debug/Logging/LogRecord.cpp
  DaemonRenderer/Source/Src/Debug/Logging/Logger.cpp
  DaemonRenderer/Source/Src/Debug/RenderDoc/RenderDocHook.cpp
  DaemonRenderer/Source/Src/Windowing/Screen.cpp
  DaemonRenderer/Source/Src/Windowing/Window.cpp
Labels: Cleanup

#8 Fixed threading classes to compile with clang
  DaemonRenderer/DaemonRenderer.vcxproj
  DaemonRenderer/Source/Include/Threading/BaseSynchronizedAccess.hpp
  DaemonRenderer/Source/Include/Threading/Synchronized.hpp
  DaemonRenderer/Source/Include/Threading/SynchronizedAccess.hpp
  DaemonRenderer/Source/Src/Threading/BaseSynchronizedAccess.inl
  DaemonRenderer/Source/Src/Threading/SynchronizedAccess.inl
  DaemonRenderer/Source/Src/Threading/ThreadSafeLockQueue.inl
Labels: Bug
